export interface JournalEntryDto {
  id: string;
  content: string;
  actionType: { id: string; name: string; icon: string | null } | null;
  author: { id: string; firstName: string; lastName: string };
  isAutoGenerated: boolean;
  assetId: string | null;
  personId: string | null;
  companyId: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface CreateJournalEntryDto {
  content: string;
  actionTypeId?: string;
  assetId?: string;
  personId?: string;
  companyId?: string;
}

export interface UpdateJournalEntryDto {
  content?: string;
  actionTypeId?: string;
}
